# Generated by Django 4.0.4 on 2022-05-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_timein_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timein_out',
            name='TimeOut',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
