# Generated by Django 4.0.4 on 2022-05-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_timein_out_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='timein_out',
            name='ParkerName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
