# Generated by Django 4.0.4 on 2022-05-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=200)),
                ('plateNumber', models.CharField(max_length=200)),
                ('parked', models.BooleanField()),
                ('ParkingSpace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.parkingspace')),
            ],
        ),
    ]
